In [1]:
import numpy as np


In [3]:
a = np.array([[5,6],[7,8]])

In [4]:
print(a)

[[5 6]
 [7 8]]


In [5]:
print(a[0,0])

5


In [6]:
c= complex(42, 1)

In [8]:
print(c)

(42+1j)


In [9]:
print(c.real)

42.0


In [11]:
print(c.imag)

1.0


In [12]:
# dtype constructor
print(np.dtype('f8'))

float64


In [13]:
# dtype attribute 
var2=np.array([1,2,3],dtype='float64')
print(var2.dtype.char)

d


In [14]:
# manipulating array shape 
# Create an array
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
print(new_arr.transpose())

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [19]:
print(arr.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
#stacking 

arr1 = np.arange(1, 10).reshape(3,3)

In [22]:
arr2 = 2*arr1
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [23]:
# Horizontal Stacking
arr3=np.hstack((arr1, arr2))
print(arr3)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [24]:
# vertical Stacking
arr3=np.vstack((arr1, arr2))
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [25]:
# Horizontal stacking using concatenate() function
arr4=np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [26]:
# depth stacking
arr7=np.dstack((arr1, arr2))
print(arr7)

[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[ 4  8]
  [ 5 10]
  [ 6 12]]

 [[ 7 14]
  [ 8 16]
  [ 9 18]]]


In [27]:
# change the data type in Numpy arrays
# Create an array
arr=np.arange(1,10).reshape(3,3)
print("Integer Array:",arr)
# Change datatype of array
arr=arr.astype(float)
# print array
print("Float Array:", arr)
# Check new data type of array
print("Changed Datatype:", arr.dtype)

Integer Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Float Array: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Changed Datatype: float64


In [28]:
# Create no copy only assignment
arr_no_copy=arr
# Create Deep Copy
arr_copy=arr.copy()
# Create shallow copy using View
arr_view=arr.view()
print("Original Array: ",id(arr))
print("Assignment: ",id(arr_no_copy))
print("Deep Copy: ",id(arr_copy))
print("Shallow Copy(View): ",id(arr_view))

Original Array:  140436613737248
Assignment:  140436613737248
Deep Copy:  140436613735088
Shallow Copy(View):  140436613735328


In [29]:
# Create NumPy Array
arr = np.arange(21,41,2)
print("Orignial Array:\n",arr)
# Boolean Indexing
print("After Boolean Condition:",arr[arr>30])

Orignial Array:
 [21 23 25 27 29 31 33 35 37 39]
After Boolean Condition: [31 33 35 37 39]
